export const INITIAL_PI_DATA = [
    {
        id: 1,
        piNo: 'EBST 03/2026',
        refNo: 'TMKL_0326_TL',
        originalDate: '16 FEBRUARY 2026',
        rev: '1',
        seller: 'K.L. INTERFOOD CO., LTD.\n58/76 MOO 3 KHLONG KLUEA, PAKKRET, 11120 NONTHABURI, THAILAND',
        buyer: 'EB SERVICES COMPANY LIMITED\nNO. 163 PHAN DANG LUU STREET, CAU KIEU WARD, HO CHI MINH CITY, VIETNAM\nTEL: (84-8) 3995 8368 (EXT: 88579), FAX: (84-8) 3995 8475',
        consignee: 'EB SERVICES COMPANY LIMITED\nNO. 163 PHAN DANG LUU STREET, CAU KIEU WARD, HO CHI MINH CITY, VIETNAM',
        notifyParty: 'EB SERVICES COMPANY LIMITED\nNO. 163 PHAN DANG LUU STREET, CAU KIEU WARD, HO CHI MINH CITY, VIETNAM',
        incoterm: 'CIF Ho Chi Minh, Cat Lai port, Vietnam',
        countryOfOrigin: 'THAILAND',
        shipmentMonth: '2nd Week of May 2026',
        portOfLoading: 'Bangkok Port, Thailand',
        portOfDischarge: 'Ho Chi Minh, Cat Lai port, Vietnam',
        destination: 'Ho Chi Minh, Cat Lai port, Vietnam',
        totals: {
            fobBangkok: '',
            freight: '',
            insurance: '',
            grandTotal: '33,372.50'
        },
        totalAmountLabel: 'THIRTY THREE THOUSAND THREE HUNDRED SEVENTY TWO US DOLLARS AND FIFTY CENTS',
        totalAmountValue: '33,372.50',
        quantityDescriptions: 'TOTAL: 1X20\'RF / 670 CARTONS / N.W. 5,791.00 KGS / G.W. 7,467.00 KGS',
        packaging: 'The goods shall be packed using our standard packing size and brand only. Any additional requirements, such as stickers, changes in packaging size, or other modifications, will be subject to additional costs. Such additional costs shall be charged under this contract. Additional cost: USD ……………',
        paymentTerm: '100% within 20 days after receiving date in the warehouse of EB SERVICE S COMPANY LIMITED and based on released report of container from shipping line. Buyer must pick up container from ETA port as soon as possible to avoid demurage & detention charge. And sign within 7 days from issuing date of this Proforma Invoice to confirm all terms and condition in this contract.',
        deposit: 'N/A',
        shippingDocuments: 'Standard shipping documents : Invoice, Packing List, Original BL, Certificate of Origin & Phytosanitary Certificate.\nAdditional documents : Form D, Fumigation, Insurance, Extra cost : …………………...…. USD',
        validity: 'This contract shall be valid for seven (7) days from the issuance date of this Proforma Invoice. This contract must be signed and affixed with the company stamp within the same period.',
        bankCharges: 'All bank charges incurred outside Thailand, including intermediary bank charges, shall be borne by the Buyer, while Bank charges incurred within Thailand shall be borne by the Seller.',
        bankName: 'THE SIAM COMMERCIAL BANK PUBLIC COMPANY LIMITED',
        branch: 'MUANGTHONG THANI',
        address: '453 BOND STREET ROAD,BAN MAI, PAK KRET, NONTHABURI 11120,THAILAND',
        accountName: 'K.L. INTERFOOD CO., LTD.',
        accountNo: '328 245705 5',
        swiftCode: 'SICOTHBK',
        shippingMarks: 'NATCHA / PRODUCT OF THAILAND',
        items: [
            {
                shipment: '2nd WEEK OF MAY 2026',
                conNo: '1',
                productDescription: 'SWEET TAMARIND\nECONOMIC GRADE, KUNTI VARIETY, STEAMED.\nSIZE: 2 PODS AND UP. 1 POD MAXIMUM OF 20 PCS APPROX 100g - Spec as per PI page no. 4/4',
                itemCode: 'SWEET-TAM-KUNTI-100G',
                brand: 'NATCHA',
                nw: '400GX20BOXES',
                nwKg: '8.00',
                packedW: 'N/A',
                packedWKg: 'N/A',
                gwKgCrt: '10.00',
                qtyCarton: '470',
                totalNwKg: '3,760.05',
                totalGwKg: '4,700.00',
                priceUsd: '34.75',
                perCtn: 'N/A',
                fumigation: 'N/A',
                amountUsd: '16,332.50'
            },
            {
                shipment: '2nd WEEK OF MAY 2026',
                conNo: '2',
                productDescription: 'SWEET TAMARIND\nECONOMIC GRADE, KUNTI VARIETY, STEAMED.\nSIZE: 2 PODS AND UP. 1 POD MAXIMUM OF 10 PCS APPROX 50g - Spec as per PI page no. 4/4',
                itemCode: 'SWEET-TAM-KUNTI-50G',
                brand: 'NATCHA',
                nw: '225GX40BOXES',
                nwKg: '9.00',
                packedW: 'N/A',
                packedWKg: 'N/A',
                gwKgCrt: '11.00',
                qtyCarton: '95',
                totalNwKg: '855.00',
                totalGwKg: '1,045.00',
                priceUsd: '39.00',
                perCtn: 'N/A',
                fumigation: 'N/A',
                amountUsd: '3,705.00'
            },
            {
                shipment: '2nd WEEK OF MAY 2026',
                conNo: '3',
                productDescription: 'SWEET TAMARIND PEEL OFF WITH SEED\nECONOMIC GRADE, KUNTI VARIETY, STEAMED.\nSIZE: 3 PODS AND UP.\n1-2 PODS MAXIMUM OF 20-25%',
                itemCode: 'SWEET-TAM-PEEL-SEED',
                brand: 'NATCHA',
                nw: '200GX56BOXES',
                nwKg: '11.20',
                packedW: 'N/A',
                packedWKg: 'N/A',
                gwKgCrt: '16.40',
                qtyCarton: '60',
                totalNwKg: '672.00',
                totalGwKg: '984.00',
                priceUsd: '130.00',
                perCtn: 'N/A',
                fumigation: 'N/A',
                amountUsd: '7,800.00'
            },
            {
                shipment: '2nd WEEK OF MAY 2026',
                conNo: '4',
                productDescription: 'DRIED HONEY TAMARIND\nSIZE: 2 PODS AND UP.\n1 POD MAXIMUM OF 30g',
                itemCode: 'DRIED-HONEY-TAM-30G',
                brand: 'NATCHA',
                nw: '200GX56BOXES',
                nwKg: '11.20',
                packedW: 'N/A',
                packedWKg: 'N/A',
                gwKgCrt: '16.40',
                qtyCarton: '45',
                totalNwKg: '504.05',
                totalGwKg: '738.00',
                priceUsd: '123.00',
                perCtn: 'N/A',
                fumigation: 'N/A',
                amountUsd: '5,535.00'
            }
        ],
        totalNw: '5,791.00',
        totalGw: '7,467.00',
        totalQty: '670',
        currentStepIndex: 2
    },
    {
        id: 2,
        piNo: 'ELST 05/2026',
        refNo: 'KL-S2603 [PO#62001608]',
        originalDate: '24 APRIL 2026',
        rev: '1',
        seller: 'K.L. INTERFOOD CO., LTD.\n670/63 PHAHONYOTHIN RD., SAMSEANNAI, PHAYATHAI, BANGKOK 10400 THAILAND',
        buyer: 'EASTLAND FOOD CORPORATION\n8305 STAYTON DRIVE, SUITE C.JESSUP, MARYLAND 20794, U.S.A.',
        consignee: 'SAME AS ABOVE',
        notifyParty: 'SAME AS ABOVE',
        incoterm: 'FOB Bangkok, Thailand',
        countryOfOrigin: 'THAILAND',
        shipmentMonth: '3rd Week of July 2026',
        portOfLoading: 'Bangkok Port, Thailand',
        portOfDischarge: 'Charleston, SC, USA',
        destination: 'Charleston, SC, USA',
        totals: {
            fobBangkok: '99,130.00',
            freight: '-',
            insurance: '',
            grandTotal: '99,130.00'
        },
        totalAmountLabel: 'NINETY NINE THOUSAND ONE HUNDRED AND THIRTY US DOLLARS ONLY',
        totalAmountValue: '99,130.00',
        quantityDescriptions: 'TOTAL: 1 X 40\' HCRT CONTAINER / 2,140 CARTONS / N.W. 16,472.40 KGS / G.W. 20,004.40 KGS',
        packaging: 'The cargo are packed by our standard packaging only. This contact does not apply for OEM term. Additional requirements such as stickers, the changes on packaging size and other changes are subject to additional cost which will be subject on this contract. The extra cost is…............................USD.',
        paymentTerm: '100% T/T payment after arrival and pass FDA',
        deposit: 'N/A',
        shippingDocuments: 'Standard shipping documents include: Commercial Invoice, Packing List, Original Bill of Lading (B/L), Certificate of Origin, and Phytosanitary Certificate.\nAdditional documents : ………..………………...…… , Extra cost : …………………...…. USD',
        validity: 'This contract shall be valid for seven (7) days from the issuance date of this Proforma Invoice. This contract must be signed and affixed with the company stamp within the same period.',
        bankCharges: 'All bank charges incurred outside Thailand, including intermediary bank charges, shall be borne by the Buyer, while Bank charges incurred within Thailand shall be borne by the Seller.',
        bankName: 'THE SIAM COMMERCIAL BANK PUBLIC COMPANY LIMITED',
        branch: 'MUANGTHONG THANI',
        address: '453 BOND STREET ROAD,BAN MAI, PAK KRET, NONTHABURI 11120,THAILAND',
        accountName: 'K.L. INTERFOOD CO., LTD.',
        accountNo: '328 245705 5',
        swiftCode: 'SICOTHBK',
        shippingMarks: 'ASIAN BEST / USA SHIPMENT',
        items: [
            {
                shipment: '3RD WEEK OF JUL 2026',
                conNo: '1',
                productDescription: 'DRIED TAMARIND\nITEM CODE: 13506910',
                itemCode: '13506910',
                brand: 'ASIAN BEST',
                nw: '454GX16P',
                nwKg: '7.26',
                packedW: '524GX16P',
                packedWKg: '8.38',
                gwKgCrt: '8.38',
                qtyCarton: '1340',
                totalNwKg: '9,728.40',
                totalGwKg: '12,140.40',
                priceUsd: '49.50',
                perCtn: 'N/A',
                fumigation: 'N/A',
                amountUsd: '66,330.00'
            },
            {
                shipment: '3RD WEEK OF JUL 2026',
                conNo: '1',
                productDescription: 'DRIED TAMARIND\nITEM CODE: 13506914\nTAMARIND PASTE',
                itemCode: '13506914',
                brand: 'ASIAN BEST',
                nw: '400GX24P',
                nwKg: '9.60',
                packedW: '400GX24P',
                packedWKg: '10.60',
                gwKgCrt: '10.60',
                qtyCarton: '400',
                totalNwKg: '3,840.00',
                totalGwKg: '4,240.00',
                priceUsd: '49.00',
                perCtn: 'N/A',
                fumigation: 'N/A',
                amountUsd: '19,600.00'
            },
            {
                shipment: '3RD WEEK OF JUL 2026',
                conNo: '1',
                productDescription: 'DRIED TAMARIND\nITEM CODE: 13506920',
                itemCode: '13506920',
                brand: 'ASIAN BEST',
                nw: '454GX16P',
                nwKg: '7.26',
                packedW: '524GX16P',
                packedWKg: '8.38',
                gwKgCrt: '8.38',
                qtyCarton: '400',
                totalNwKg: '2,904.00',
                totalGwKg: '3,624.00',
                priceUsd: '33.00',
                perCtn: 'N/A',
                fumigation: 'N/A',
                amountUsd: '13,200.00'
            }
        ],
        totalNw: '16,472.40',
        totalGw: '20,004.40',
        totalQty: '2,140',
        currentStepIndex: 3
    },
    {
        id: 3,
        piNo: 'SFST 02/2026',
        refNo: '7939',
        originalDate: '22 MAY 2026',
        rev: '1',
        seller: 'K.L. INTERFOOD CO., LTD.\n58/76 Moo 3, Khlong Kluer, Pakkred, Nonthaburi 11120, Thailand',
        buyer: 'DAWN & COMPANY (LONDON)LTD T/A SUPERFOODS\n128 CITY ROAD, LONDON, EC1V 2NX UNITED KINGDOM\nVAT NO. GB 665 5732 08 EORI: GB665573208000',
        consignee: 'DAWN & COMPANY (LONDON)LTD T/A SUPERFOODS\n128 CITY ROAD, LONDON, EC1V 2NX UNITED KINGDOM',
        notifyParty: 'KUEHNE +NAGEL KN PERISHABLE HANDLING CENTRE (PHC)\nBUILDING 1235 EASTERN PERIMETER ROAD HATTON CROSS HEATHROW AIRPORT TW6 2SQ\nTEL : +44 208 283 0421',
        incoterm: 'C&I Felixstowe, U.K.',
        countryOfOrigin: 'THAILAND',
        shipmentMonth: 'June 2026',
        portOfLoading: 'Bangkok Port, Thailand',
        portOfDischarge: 'Felixstowe, U.K.',
        destination: 'Felixstowe, U.K.',
        totals: {
            fobBangkok: '49,532.00',
            freight: 'TBA',
            insurance: '250.00',
            grandTotal: '49,782.00'
        },
        totalAmountLabel: 'FORTY NINE THOUSAND SEVEN HUNDRED AND EIGHTY-TWO US DOLLARS ONLY',
        totalAmountValue: '49,782.00',
        quantityDescriptions: 'TOTAL: 1 x 40HCRF / 1,624 CARTONS / N.W. 11,368.00 KGS / G.W. 14,616.00 KGS',
        packaging: 'The goods shall be packed using our standard packing size and brand only. Any additional requirements, such as stickers, changes in packaging size, or other modifications, will be subject to additional costs. Such additional costs shall be charged under this contract. Additional cost: USD ……………',
        paymentTerm: '30% advance TT deposit of 14,934.60 USD within 7 days from issuing date of this Proforma Invoice and 60% on documents released and 10% after arrival within 7 days',
        deposit: '30% Deposit',
        shippingDocuments: 'Standard shipping documents include: Commercial Invoice, Packing List, Original Bill of Lading (B/L), Certificate of Origin, and Phytosanitary Certificate.\nAdditional documents : ………..………………...…… , Extra cost : …………………...…. USD',
        validity: 'This contract shall be valid for seven (7) days from the issuance date of this Proforma Invoice. This contract must be signed and affixed with the company stamp within the same period.',
        bankCharges: 'All bank charges incurred outside Thailand, including intermediary bank charges, shall be borne by the Buyer, while Bank charges incurred within Thailand shall be borne by the Seller.',
        bankName: 'THE SIAM COMMERCIAL BANK PUBLIC COMPANY LIMITED',
        branch: 'MUANGTHONG THANI',
        address: '453 BOND STREET ROAD,BAN MAI, PAK KRET, NONTHABURI 11120,THAILAND',
        accountName: 'K.L. INTERFOOD CO., LTD.',
        accountNo: '328 245705 5',
        swiftCode: 'SICOTHBK',
        shippingMarks: 'ELEPHANT / NATHCA / UK SHIPMENT',
        items: [
            {
                shipment: 'JUN 2026',
                conNo: '1',
                productDescription: 'SWEET TAMARIND -\nKUNTI - MEDIUM - STEAMED',
                itemCode: 'SWEET-TAM-KUNTI-MED',
                brand: 'ELEPHANT/NATHCA',
                nw: '350GX20P',
                nwKg: '7.00',
                packedW: '400GX20P',
                packedWKg: '8.00',
                gwKgCrt: '8.00',
                qtyCarton: '1624',
                totalNwKg: '11,368.00',
                totalGwKg: '14,616.00',
                priceUsd: '30.50',
                perCtn: 'N/A',
                fumigation: 'N/A',
                amountUsd: '49,532.00'
            }
        ],
        totalNw: '11,368.00',
        totalGw: '14,616.00',
        totalQty: '1,624',
        currentStepIndex: 4
    }
];
